// flow-typed signature: 754af46fd4b82a136d51ea8c4b50d5f0
// flow-typed version: <<STUB>>/@redneckz/react-bem-helper_v1.1.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@redneckz/react-bem-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@redneckz/react-bem-helper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@redneckz/react-bem-helper/dist/react-bem-helper' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/dist/react-bem-helper.min' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/es/react-bem-helper' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/lib/react-bem-helper' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/bem-naming-factory/bem-naming-factory' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/bem-naming-factory/bem-naming-factory.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/bem-naming-factory/index' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/block/base-block.integrational.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/block/base-block' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/block/base-block.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/block/block-context-types' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/block/block.integrational.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/block/block' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/block/block.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/block/index' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/config' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/element/element.integrational.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/element/element' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/element/element.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/element/index' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/index' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/modifier/index' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/modifier/modifier-predicates' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/modifier/modifier-predicates.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/modifier/modifier' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/modifier/modifier.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/tag/index' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/tag/tag.integrational.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/tag/tag' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/tag/tag.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/utils/class-names-list' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/utils/class-names-list.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/utils/index' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/utils/kebab-case' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/utils/kebab-case.spec' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/utils/pick' {
  declare module.exports: any;
}

declare module '@redneckz/react-bem-helper/src/utils/pick.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@redneckz/react-bem-helper/dist/react-bem-helper.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/dist/react-bem-helper'>;
}
declare module '@redneckz/react-bem-helper/dist/react-bem-helper.min.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/dist/react-bem-helper.min'>;
}
declare module '@redneckz/react-bem-helper/es/react-bem-helper.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/es/react-bem-helper'>;
}
declare module '@redneckz/react-bem-helper/lib/react-bem-helper.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/lib/react-bem-helper'>;
}
declare module '@redneckz/react-bem-helper/src/bem-naming-factory/bem-naming-factory.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/bem-naming-factory/bem-naming-factory'>;
}
declare module '@redneckz/react-bem-helper/src/bem-naming-factory/bem-naming-factory.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/bem-naming-factory/bem-naming-factory.spec'>;
}
declare module '@redneckz/react-bem-helper/src/bem-naming-factory/index.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/bem-naming-factory/index'>;
}
declare module '@redneckz/react-bem-helper/src/block/base-block.integrational.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/block/base-block.integrational.spec'>;
}
declare module '@redneckz/react-bem-helper/src/block/base-block.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/block/base-block'>;
}
declare module '@redneckz/react-bem-helper/src/block/base-block.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/block/base-block.spec'>;
}
declare module '@redneckz/react-bem-helper/src/block/block-context-types.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/block/block-context-types'>;
}
declare module '@redneckz/react-bem-helper/src/block/block.integrational.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/block/block.integrational.spec'>;
}
declare module '@redneckz/react-bem-helper/src/block/block.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/block/block'>;
}
declare module '@redneckz/react-bem-helper/src/block/block.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/block/block.spec'>;
}
declare module '@redneckz/react-bem-helper/src/block/index.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/block/index'>;
}
declare module '@redneckz/react-bem-helper/src/config.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/config'>;
}
declare module '@redneckz/react-bem-helper/src/element/element.integrational.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/element/element.integrational.spec'>;
}
declare module '@redneckz/react-bem-helper/src/element/element.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/element/element'>;
}
declare module '@redneckz/react-bem-helper/src/element/element.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/element/element.spec'>;
}
declare module '@redneckz/react-bem-helper/src/element/index.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/element/index'>;
}
declare module '@redneckz/react-bem-helper/src/index.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/index'>;
}
declare module '@redneckz/react-bem-helper/src/modifier/index.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/modifier/index'>;
}
declare module '@redneckz/react-bem-helper/src/modifier/modifier-predicates.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/modifier/modifier-predicates'>;
}
declare module '@redneckz/react-bem-helper/src/modifier/modifier-predicates.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/modifier/modifier-predicates.spec'>;
}
declare module '@redneckz/react-bem-helper/src/modifier/modifier.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/modifier/modifier'>;
}
declare module '@redneckz/react-bem-helper/src/modifier/modifier.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/modifier/modifier.spec'>;
}
declare module '@redneckz/react-bem-helper/src/tag/index.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/tag/index'>;
}
declare module '@redneckz/react-bem-helper/src/tag/tag.integrational.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/tag/tag.integrational.spec'>;
}
declare module '@redneckz/react-bem-helper/src/tag/tag.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/tag/tag'>;
}
declare module '@redneckz/react-bem-helper/src/tag/tag.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/tag/tag.spec'>;
}
declare module '@redneckz/react-bem-helper/src/utils/class-names-list.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/utils/class-names-list'>;
}
declare module '@redneckz/react-bem-helper/src/utils/class-names-list.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/utils/class-names-list.spec'>;
}
declare module '@redneckz/react-bem-helper/src/utils/index.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/utils/index'>;
}
declare module '@redneckz/react-bem-helper/src/utils/kebab-case.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/utils/kebab-case'>;
}
declare module '@redneckz/react-bem-helper/src/utils/kebab-case.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/utils/kebab-case.spec'>;
}
declare module '@redneckz/react-bem-helper/src/utils/pick.js' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/utils/pick'>;
}
declare module '@redneckz/react-bem-helper/src/utils/pick.spec.jsx' {
  declare module.exports: $Exports<'@redneckz/react-bem-helper/src/utils/pick.spec'>;
}
